# Generated by Django 2.1.2 on 2018-12-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0023_remove_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_tried_count', models.IntegerField()),
                ('users_solved_count', models.IntegerField()),
                ('submission_count', models.IntegerField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='data.Task')),
            ],
        ),
    ]
