# Generated by Django 2.1.2 on 2018-12-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20181219_1618'),
        ('stats', '0002_auto_20181210_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_solved_count', models.IntegerField(default=0)),
                ('tasks_tried_count', models.IntegerField(default=0)),
                ('rank', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='data.UserProfile')),
            ],
        ),
    ]
