# Generated by Django 2.1.2 on 2019-03-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20190325_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatistics',
            name='difficulty_score',
            field=models.IntegerField(default=1),
        ),
    ]
