# Generated by Django 2.1.2 on 2019-03-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_taskstatistics_difficulty_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
