# Generated by Django 2.1.2 on 2019-03-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_auto_20190328_1320'),
        ('stats', '0006_userstatistics_total_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_submissions', to='data.UserProfile')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Submission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_submissions', to='data.Task')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bestsubmission',
            unique_together={('profile', 'task')},
        ),
    ]
