# Generated by Django 3.0.5 on 2020-08-20 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0006_remove_ladder_points_earned'),
        ('stats', '0007_auto_20190328_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(null=True)),
                ('ladder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='ladders.Ladder')),
            ],
        ),
    ]
