# Generated by Django 3.0.5 on 2020-08-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0050_userprofile_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='LadderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('RUN', 'In Progress'), ('EXP', 'Expired'), ('COM', 'Completed')], max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('end_on', models.DateTimeField()),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ladders.Ladder')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Task')),
            ],
        ),
    ]
