# Generated by Django 3.0.5 on 2020-08-16 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laddertask',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='laddertask',
            name='end_on',
        ),
        migrations.AddField(
            model_name='laddertask',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(hours=24)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laddertask',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 16, 47, 22, 144802, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laddertask',
            name='status',
            field=models.CharField(choices=[('RUN', 'In Progress'), ('EXP', 'Expired'), ('COM', 'Completed'), ('NEW', 'New'), ('LOC', 'Locked')], max_length=3),
        ),
    ]
