# Generated by Django 3.0.5 on 2020-08-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0002_auto_20200816_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laddertask',
            name='started_on',
            field=models.DateTimeField(null=True),
        ),
    ]
