# Generated by Django 3.0.5 on 2020-08-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0004_auto_20200816_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladder',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
    ]
