# Generated by Django 3.0.5 on 2020-08-20 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0005_ladder_points_earned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladder',
            name='points_earned',
        ),
    ]
