# Generated by Django 2.0.5 on 2018-10-09 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.CharField(choices=[('ac', 'AtCoder'), ('ia', 'Infoarena'), ('poj', 'POJ')], max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('homepage', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=256)),
                ('submitted_on', models.DateTimeField()),
                ('language', models.CharField(max_length=256)),
                ('source_size', models.IntegerField()),
                ('verdict', models.CharField(choices=[('AC', 'Accepted'), ('CE', 'Compile Error'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('WA', 'Wrong Answer')], max_length=256)),
                ('score', models.IntegerField(null=True)),
                ('exec_time', models.IntegerField(null=True)),
                ('memory_used', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=256)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='UserHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=256)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Judge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.User')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.UserHandle'),
        ),
        migrations.AddField(
            model_name='submission',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Task'),
        ),
    ]
