# Generated by Django 2.0.5 on 2018-10-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20181009_1018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('task', 'submission_id')},
        ),
    ]
