# Generated by Django 2.0.5 on 2018-10-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20181009_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_on']},
        ),
    ]
