# Generated by Django 2.0.5 on 2018-10-19 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('members', models.ManyToManyField(to='data.User')),
            ],
        ),
    ]
