# Generated by Django 2.0.5 on 2018-10-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181009_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='lucianbicsi', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
