# Generated by Django 2.0.5 on 2018-10-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20181009_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=256)),
                ('submitted_on', models.DateTimeField()),
                ('language', models.CharField(max_length=256)),
                ('source_size', models.IntegerField()),
                ('verdict', models.CharField(choices=[('AC', 'Accepted'), ('CE', 'Compile Error'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('WA', 'Wrong Answer')], max_length=256)),
                ('score', models.IntegerField(null=True)),
                ('exec_time', models.IntegerField(null=True)),
                ('memory_used', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.UserHandle')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Task')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('task', 'submission_id')},
        ),
    ]
