# Generated by Django 2.1.2 on 2018-10-31 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20181019_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='judge_id',
            field=models.CharField(choices=[('ac', 'AtCoder'), ('ia', 'Infoarena'), ('poj', 'POJ'), ('cf', 'Codeforces')], max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='source_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userhandle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handles', to='data.User'),
        ),
    ]
