# Generated by Django 2.1.2 on 2018-11-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20181031_0939'),
        ('data', '0012_auto_20181031_0911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
