# Generated by Django 2.1.2 on 2018-11-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20181102_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='members',
            field=models.ManyToManyField(related_name='assigned_groups', to='data.UserProfile'),
        ),
    ]
