# Generated by Django 2.1.2 on 2018-11-02 19:10

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20181102_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=data.models.user_directory_path),
        ),
    ]
