# Generated by Django 2.1.2 on 2018-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='judge_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
