# Generated by Django 2.1.2 on 2018-11-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20181110_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_owned', to='data.UserProfile'),
        ),
    ]
