# Generated by Django 2.1.2 on 2018-11-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20181117_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
