# Generated by Django 2.1.2 on 2018-12-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_remove_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhandle',
            name='photo_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
