# Generated by Django 2.1.2 on 2018-12-19 16:18

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20181219_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=256),
        ),
    ]
