# Generated by Django 2.1.2 on 2018-12-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20181219_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
