# Generated by Django 2.1.2 on 2019-02-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_task_modified_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('submission_id', 'author')},
        ),
    ]
