# Generated by Django 2.2.6 on 2019-10-23 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_taskstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgetaskstatistic',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_statistic', to='data.Task'),
        ),
    ]
