# Generated by Django 2.2.6 on 2019-10-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_task_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'member'), ('owner', 'owner')], default='member', max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.UserGroup')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.UserProfile')),
            ],
            options={
                'unique_together': {('profile', 'group')},
            },
        ),
    ]
