# Generated by Django 2.2.6 on 2019-10-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_auto_20191028_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='members',
        ),
    ]
