# Generated by Django 2.2.6 on 2019-10-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_remove_usergroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='members',
            field=models.ManyToManyField(related_name='assigned_groups', through='data.GroupMember', to='data.UserProfile'),
        ),
    ]
