# Generated by Django 2.2.7 on 2019-12-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_usergroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contest_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
