# Generated by Django 2.2.7 on 2019-12-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_task_contest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contest_id',
        ),
    ]
