# Generated by Django 2.2.9 on 2019-12-24 18:36

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_remove_task_contest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='statement_md',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
