# Generated by Django 2.2.9 on 2019-12-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_task_statement_md'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='statement_md',
            new_name='formatted_statement',
        ),
    ]
