# Generated by Django 2.2.9 on 2019-12-24 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_remove_task_formatted_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='statement',
        ),
        migrations.CreateModel(
            name='TaskStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user_modified', models.BooleanField(default=False)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statement', to='data.Task')),
            ],
        ),
    ]
