# Generated by Django 2.2.9 on 2019-12-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_auto_20191224_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatement',
            old_name='user_modified',
            new_name='modified_by_user',
        ),
    ]
