# Generated by Django 2.2.9 on 2019-12-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_taskstatement_examples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='memory_limit_kb',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_limit_ms',
        ),
        migrations.AddField(
            model_name='taskstatement',
            name='input_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='taskstatement',
            name='memory_limit_kb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstatement',
            name='output_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='taskstatement',
            name='time_limit_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
