# Generated by Django 3.0.5 on 2020-08-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_auto_20191225_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
