# Generated by Django 3.0.5 on 2020-11-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=256),
        ),
    ]
