# Generated by Django 2.1.2 on 2018-10-31 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20181019_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksheet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
