# Generated by Django 2.1.2 on 2018-11-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20181031_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksheet',
            old_name='slice_id',
            new_name='sheet_id',
        ),
    ]
