# Generated by Django 2.1.2 on 2018-11-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20181102_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksheet',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='assigned_sheets', to='data.UserGroup'),
        ),
        migrations.AlterField(
            model_name='tasksheet',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='assigned_sheets', to='data.UserProfile'),
        ),
    ]
