# Generated by Django 2.1.2 on 2018-11-19 12:28

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20181102_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksheet',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
