# Generated by Django 2.1.2 on 2018-11-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_remove_userprofile_username'),
        ('info', '0014_auto_20181121_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignation',
            new_name='Assignment',
        ),
    ]
