# Generated by Django 2.1.2 on 2018-11-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_remove_userprofile_username'),
        ('info', '0015_auto_20181122_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksheet',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.UserProfile'),
        ),
    ]
