# Generated by Django 2.1.2 on 2018-12-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20181122_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['assigned_on']},
        ),
    ]
