# Generated by Django 2.1.2 on 2018-12-10 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_userhandle_photo_url'),
        ('info', '0018_auto_20181207_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tasks', to='data.UserProfile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_users', to='data.Task')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favoritetask',
            unique_together={('task', 'profile')},
        ),
    ]
