# Generated by Django 2.1.2 on 2019-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20190205_1818'),
        ('info', '0021_auto_20190326_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksheet',
            name='tasks',
            field=models.ManyToManyField(through='info.TaskSheetTask', to='data.Task'),
        ),
    ]
