# Generated by Django 2.1.2 on 2019-03-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20190327_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('ordering_id', '-assigned_on')},
        ),
        migrations.AddField(
            model_name='tasksheettask',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
