# Generated by Django 2.2.6 on 2019-10-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_auto_20190327_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='end_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
