# Generated by Django 2.1.2 on 2019-10-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_assignment_end_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hide_submissions_before_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
