# Generated by Django 2.2.6 on 2019-10-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_auto_20191014_1117'),
        ('info', '0027_assignment_hide_submissions_before_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTaskTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tags', to='data.UserProfile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tags', to='data.Task')),
            ],
            options={
                'unique_together': {('task', 'profile', 'name')},
            },
        ),
    ]
