# Generated by Django 2.2.9 on 2020-04-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_auto_20191028_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksheettask',
            name='score',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
