# Generated by Django 3.0.5 on 2020-11-02 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_auto_20201102_1444'),
        ('info', '0030_tasksheettask_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='data.UserGroup'),
        ),
    ]
