# Generated by Django 2.0.5 on 2018-10-09 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0008_auto_20181009_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsSlice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('tasks', models.ManyToManyField(to='data.Task')),
                ('users', models.ManyToManyField(to='data.User')),
            ],
        ),
    ]
