# Generated by Django 2.0.5 on 2018-10-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_resultsslice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsslice',
            name='slice_id',
            field=models.CharField(default='seminarasd2018', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
