# Generated by Django 2.0.5 on 2018-10-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_resultsslice_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsslice',
            name='users',
            field=models.ManyToManyField(blank=True, to='data.User'),
        ),
    ]
