# Generated by Django 2.0.5 on 2018-10-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20181019_0416'),
        ('info', '0005_auto_20181019_0421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultsSlice',
            new_name='TaskSheet',
        ),
    ]
