# Generated by Django 2.0.5 on 2018-10-19 04:26

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('info', '0006_auto_20181019_0422'),
    ]

    operations = [
    ]
