# Generated by Django 2.0.5 on 2018-10-19 04:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('info', '0007_auto_20181019_0426'),
    ]

    operations = [
    ]
