# Generated by Django 3.0.5 on 2020-11-02 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0051_auto_20201102_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileScheduleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_on', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_info', to='data.UserProfile')),
            ],
        ),
    ]
