# Generated by Django 3.0.5 on 2020-11-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_auto_20201102_1444'),
        ('schedule', '0005_auto_20201102_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskScheduleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_on', models.DateField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_info', to='data.Task')),
            ],
        ),
    ]
